### ISSUE TITLE
Possible error due to corrupt backup. Possible to fix?

### ISSUE THREAD

**Issue by loonathedorm** [Linuxndroid/WA-GD#1]
I'm getting the error below:
```
Traceback (most recent call last):
  File "/home/orbitsrv/WA-GD/WhatsAppGDExtract.py", line 248, in main
    print("Backup Size:{} Upload Time: {}".format(human_size(int(backup["sizeBytes"])), backup["updateTime"]))
KeyError: 'sizeBytes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/orbitsrv/WA-GD/WhatsAppGDExtract.py", line 260, in <module>
    main(sys.argv)
  File "/home/orbitsrv/WA-GD/WhatsAppGDExtract.py", line 253, in main
    human_size(int(backup["sizeBytes"])),
KeyError: 'sizeBytes'
````

Is it possible to fix? I have a doubt that it could be because my backup is corrupt and hence shows the size as 0 bytes which the current code might not be expecting. Is it possible to fix it ad allow to download the corrupted backup as well?

**Comment by Linuxndroid** [comment]
try to fix this,, install requests packages
Command `pip install gpsoauth && pip install requests==2.23.0`
hope so fix it..
